
[workspace]
members = [
  "crates/symgraph-cli",
  "crates/symgraph-core",
  "crates/symgraph-discovery",
  "crates/symgraph-cxx",
  "crates/symgraph-rust",
  "crates/symgraph-models"
]
resolver = "2"
